name: LingChat
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.12
  - pip
  - cpuonly
  - pytorch>=2.5.0,<2.6.0
  - pyperclip
  - pip:
      - fastapi>=0.116.1,<0.117.0
      - uvicorn>=0.35.0,<0.36.0
      - requests>=2.32.4,<3.0.0
      - aiohttp>=3.12.11,<4.0.0
      - transformers>=4.52.4,<4.53.0
      - pywebview>=5.4,<6.0.0
      - openai>=1.85.0,<2.0.0
      - platformdirs>=4.3.8,<5.0.0
      - python-multipart>=0.0.20,<0.1.0
      - websockets>=15.0.1,<16.0.0
      - mss>=10.0.0,<11.0.0
      - google-generativeai>=0.8.5,<0.9.0
      - py7zr>=1.0.0,<2.0.0
      - poetry-core>=2.1.3,<3.0.0
      - sentence-transformers>=5.0.0,<6.0.0
      - chromadb>=1.0.0,<2.0.0